DROP TABLE BOOK;

CREATE TABLE BOOK(
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_BOOK_ID;

INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '자바의 정석', '남궁성', '한빛');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '해리포터와 마법사의 돌', '홍길동', '문학인');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '어린왕자', '토마스', '사람');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '1984', '조지 오웰', '열린');
INSERT INTO BOOK
VALUES(SEQ_BOOK_ID.NEXTVAL, '데이터베이스개론', '허밍웨이', '한빛');

COMMIT;