-- 사용자 계정 생성1
CREATE USER C##W3CTEST IDENTIFIED BY W3CTEST;


-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO C##W3CTEST;

--뷰 생성
GRANT CREATE VIEW TO C##W3CTEST


-- 테이블스페이스 설정
ALTER USER C##W3CTEST DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;