-- 사용자 계정 생성
CREATE USER c##TEST1 IDENTIFIED BY TEST;


-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##TEST1;


-- 테이블스페이스 설정
ALTER USER C##TEST1 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--1.
DROP TABLE TEACHER;
CREATE TABLE TEACHER(
    TEACHER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(21) NOT NULL,
    EMAIL VARCHAR2(40) UNIQUE,
    HIRE_DATE DATE,
    SUBJECT VARCHAR2(40)
);

INSERT INTO TEACHER VALUES();

DROP TABLE LECTURE;
CREATE TABLE LECTURE(
    LECTURE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(40) NOT NULL, 
    TEACHER_ID NUMBER REFERENCES TEACHER,
    INDEX_COUNT NUMBER DEFAULT 0 NOT NULL,
    CATEGORY VARCHAR2,
    START_DATE DATE NOT NULL,
    END_DATE DATE
);
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STUDENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(21) NOT NULL,
    GRADE NUMBER NOT NULL,
    EMAIL VARCHAR2(40),
    JOIN_DATE DATE
);
DROP TABLE ENROLLMENT;
CREATE TABLE ENROLLMENT(
    ENROLL_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER REFERENCES STUDENT,
    LECTURE_ID NUMBER REFERENCES LECTURE,
    ENROLL_DATE DATE NOT NULL,
    STATUS CHAR(1) CHECK(STATUS IN('Y', 'N')) NOT NULL,
    GRADE_SCORE NUMBER
);

