--1.
SELECT L.TITLE AS "강의 이름", COUNT(E.STUDENT_ID) AS "수강생 수"
FROM LECTURE L
JOIN ENROLLMENT E ON L.LECTURE_ID = E.LECTURE_ID
JOIN STUDENT S ON S.STUDENT_ID = E.STUDENT_ID
GROUP BY L.TITLE
HAVING COUNT(E.STUDENT_ID) > 0
ORDER BY COUNT(*);

--2.
SELECT TITLE AS "강의 이름", NAME AS "강사 이름", STATUS AS "수강 상태"
FROM ENROLLMENT E
JOIN LECTURE L ON E.LECTURE_ID = L.LECTURE_ID
JOIN TEACHER T ON T.TEACHER_ID = L.TEACHER_ID
WHERE E.STUDENT_ID = 1001
    AND STATUS = 'Y';

--3.
SELECT SUBJECT AS "전공", COUNT(*) AS "전공 별로 담당 중인 강의 개수"
FROM TEACHER T
JOIN LECTURE L ON L.TEACHER_ID = T.TEACHER_ID
WHERE T.SUBJECT IS NOT NULL
GROUP BY SUBJECT
ORDER BY SUBJECT;

--4.
SELECT TITLE AS "강의 이름", ROUND(AVG(GRADE_SCORE), 1) AS "평균 점수"
FROM ENROLLMENT E
JOIN LECTURE L ON L.LECTURE_ID = E.LECTURE_ID
GROUP BY TITLE
HAVING AVG(GRADE_SCORE) >= 80
ORDER BY AVG(GRADE_SCORE) DESC;

--5.
DROP TRIGGER TRG_01;
CREATE OR REPLACE TRIGGER TRG_01
AFTER INSERT ON ENROLLMENT
FOR EACH ROW
BEGIN
    IF :NEW.LECTURE_ID = 2001 THEN
        UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT + 1 WHERE LECTURE_ID = 2001;
    ELSIF :NEW.LECTURE_ID = 2002 THEN
        UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT + 1 WHERE LECTURE_ID = 2002;
    ELSIF :NEW.LECTURE_ID = 2003 THEN
        UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT + 1 WHERE LECTURE_ID = 2003;
    ELSIF :NEW.LECTURE_ID = 2004 THEN
        UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT + 1 WHERE LECTURE_ID = 2004;
    ELSIF :NEW.LECTURE_ID = 2005 THEN
        UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT + 1 WHERE LECTURE_ID = 2005;
    END IF;
END;
/

DROP TRIGGER TRG_02;
CREATE OR REPLACE TRIGGER TRG_02
AFTER DELETE ON ENROLLMENT
FOR EACH ROW
BEGIN
    IF :OLD.LECTURE_ID = 2001 THEN
    UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT - 1 WHERE LECTURE_ID = 2001;
    
    ELSIF :OLD.LECTURE_ID = 2002 THEN
    UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT - 1 WHERE LECTURE_ID = 2002;
   
    ELSIF :OLD.LECTURE_ID = 2003 THEN
    UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT - 1 WHERE LECTURE_ID = 2003;
    
    ELSIF :OLD.LECTURE_ID = 2004 THEN
    UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT - 1 WHERE LECTURE_ID = 2004;
    
    ELSIF :OLD.LECTURE_ID = 2005 THEN
    UPDATE LECTURE SET INDEX_COUNT = INDEX_COUNT - 1 WHERE LECTURE_ID = 2005;
    END IF;
END;
/