--1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, 
    TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3. ***
SELECT PROFESSOR_NAME, 
    DECODE(SUBSTR(PROFESSOR_SSN, 8, 1), 
         '1', (TO_CHAR(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), 'YYYY') - ('19' || TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'RR'), 'YY'))), 
         '2', (TO_CHAR(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), 'YYYY') - ('19' || TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'RR'), 'YY'))),
         '3', (TO_CHAR(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), 'YYYY') - ('20' || TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'RR'), 'YY'))),
         '4', (TO_CHAR(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), 'YYYY') - ('20' || TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'RR'), 'YY')))) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1';

--4. 
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

--5. EXTRACT 사용 빈도 늘리기.
SELECT STUDENT_NO, STUDENT_NAME
    --MONTHS_BETWEEN(TO_DATE(SUBSTR(ENTRANCE_DATE, 1, 2), 'RR'), TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')) /12 AS 나이
FROM TB_STUDENT
WHERE MONTHS_BETWEEN(TO_DATE(SUBSTR(ENTRANCE_DATE, 1, 2), 'RR'), TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR'))/12 > 19;

--6.
SELECT TO_CHAR(TO_DATE(20201225, 'YYYYMMDD'), 'DAY') 
FROM DUAL;

--7.
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY'),
       TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY')
FROM DUAL;

--8. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO NOT LIKE 'A%';
--WHERE ENTRANCE_DATE < '2000/01/01';

--9.
SELECT ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO AS 학과번호, COUNT(*) AS "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO, 1, 4) AS 년도, ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

--13. ***
SELECT TB_DEPARTMENT.DEPARTMENT_NO AS 학과코드명,
    NVL(COUNT(TB_STUDENT.STUDENT_NO), 0)AS "휴학생 수"
FROM TB_DEPARTMENT
LEFT JOIN TB_STUDENT 
    ON TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
    AND TB_STUDENT.ABSENCE_YN = 'Y' --휴학중인 학생들만 연결
GROUP BY TB_DEPARTMENT.DEPARTMENT_NO
ORDER BY TB_DEPARTMENT.DEPARTMENT_NO ASC;

SELECT DEPARTMENT_NO 학과코드명, COUNT(DECODE(ABSENCE_YN, 'Y', 1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14.
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY 1;

--15. ***
SELECT 
    SUBSTR(TERM_NO,1,4) AS 년도,
    SUBSTR(TERM_NO,5,2) AS 학기,
    POINT,
    -- 년도별 평점 (년도단위, 1자리 반올림)
    ROUND(AVG(POINT) OVER (PARTITION BY SUBSTR(TERM_NO,1,4)), 1) AS 년도별_평점,
    -- 전체 총평점 (학생 전체, 1자리 반올림)
    ROUND(AVG(POINT) OVER (), 1) AS 총평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
ORDER BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2);

SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1; 
