--1.
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2. 
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY MONTHS_BETWEEN(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD'))/12 ASC;

--3.
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_ADDRESS IN (SELECT STUDENT_ADDRESS 
                            FROM TB_STUDENT
                            WHERE STUDENT_ADDRESS LIKE ('%경기도%') 
                                OR STUDENT_ADDRESS LIKE ('%강원도%'))
    AND STUDENT_NO NOT LIKE 'A%';

--4. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY MONTHS_BETWEEN(TO_DATE(SUBSTR(SYSDATE, 1, 2), 'RR'), TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD'))/12 DESC;

--5.
SELECT STUDENT_NO, TO_CHAR(POINT, 9.99) POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO LIKE '200402'
GROUP BY STUDENT_NO, POINT
ORDER BY POINT DESC, STUDENT_NO ASC;

--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

--7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY CLASS_NAME, DEPARTMENT_NAME ASC;

--8. 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT ON TB_CLASS.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
WHERE CATEGORY = '인문사회';

--10.
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT), 1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

--11.
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12.
SELECT STUDENT_NAME, TERM_NO TERM_NAME
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_CLASS ON(TB_GRADE.CLASS_NO = TB_CLASS.CLASS_NO)
WHERE TERM_NO LIKE '2007%' 
    AND CLASS_NAME = '인간관계론';

--13. ***
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT ON TB_CLASS.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
LEFT JOIN TB_CLASS_PROFESSOR ON TB_CLASS.CLASS_NO = TB_CLASS_PROFESSOR.CLASS_NO
WHERE CATEGORY = '예체능' 
    AND TB_CLASS_PROFESSOR.PROFESSOR_NO IS NULL;

--14. ***
SELECT STUDENT_NAME, NVL(PROFESSOR_NAME,'지도교수 미지정')
FROM TB_STUDENT
LEFT JOIN TB_PROFESSOR ON TB_PROFESSOR.PROFESSOR_NO = TB_STUDENT.COACH_PROFESSOR_NO
JOIN TB_DEPARTMENT ON TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '서반아어학과';

--15. 
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, DEPARTMENT_NAME AS 학과이름, 
    AVG(POINT) AS 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING  AVG(POINT) >= 4.0;

--16. ***
SELECT TB_CLASS.CLASS_NO, TB_CLASS.CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_DEPARTMENT ON TB_DEPARTMENT.DEPARTMENT_NO = TB_CLASS.DEPARTMENT_NO
JOIN TB_GRADE ON TB_GRADE.CLASS_NO = TB_CLASS.CLASS_NO
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%'
GROUP BY TB_CLASS.CLASS_NO, TB_CLASS.CLASS_NAME;

--17. 
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN (SELECT DEPARTMENT_NO FROM tb_student
                            WHERE STUDENT_NAME = '최경희');

--18. ***
SELECT STUDENT_NO, STUDENT_NAME
FROM(SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) AS AVG
    FROM TB_STUDENT
    JOIN TB_GRADE USING(STUDENT_NO)
    WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT
                                        WHERE DEPARTMENT_NAME = '국어국문학과')
    GROUP BY STUDENT_NO, STUDENT_NAME
    ORDER BY AVG DESC)
WHERE ROWNUM = 1;

--19.
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT), 1)
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE CATEGORY = (SELECT CATEGORY
        FROM TB_DEPARTMENT
        WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;