--1.
INSERT INTO TB_CLASS_TYPE VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(05, '논문지도');

--2. 
CREATE TABLE TB_학생일반정보
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDNET_ADDRESS
        FROM TB_STUDENT);
        
--3.
DROP TABLE TB_국어국문학과;
CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO AS 학번, 
        STUDENT_NAME AS 학생이름, 
        TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR'), 'YYYY') AS 출생년도,
        PROFESSOR_NAME
    FROM TB_STUDENT
    LEFT JOIN TB_PROFESSOR ON TB_STUDENT.COACH_PROFESSOR_NO = TB_PROFESSOR.PROFESSOR_NO);
        
--4. 
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND((CAPACITY * 1.1), 0);

--5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6. 
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

--7.
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501' 
    AND STUDENT_NO = (SELECT STUDENT_NO 
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '김명훈' 
                            AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
                                                    FROM TB_DEPARTMENT
                                                    WHERE DEPARTMENT_NAME = '의학과'))
    AND CLASS_NO = (SELECT CLASS_NO 
                        FROM TB_CLASS 
                        WHERE CLASS_NAME = '피부생리학');
COMMIT;

--8. 
DELETE FROM TB_GRADE 
WHERE STUDENT_NO IN (SELECT STUDENT_NO 
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');