--1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10) PRIMARY KEY
);

--4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAEM NIT NULL;

--5.
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

--6.
ALTER TABLE TB_CLASS_TYPE 
    RENAME COLUMN NO TO CLASS_TYPE_NO);
ALTER TABLE TB_CATEGROY
    RENAME COLUMN NAME TO CATEGORY_NAME);
    
--7. 
ALTER TABLE TB_CATEGORY DROP COLUMN CATEGORY_NAME;
ALTER TABLE TB_CATEGORY 
    ADD COLUMN PK_CATEGORY_NAME PRIMARY KEY;

ALTER TABLE TB_CLASS_TYPE DROP COLUMN CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE 
    ADD COLUMN PK_CLASS_TYPE_NO PRIMARY KEY;
    
--8.
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;

--9.
ALTER TABLE TB_DEPARTMENT
    ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
    FOREIGN KEY (CATEGORY)
    REFERENCES TB_CATEGORY (CATEGORY_NAME);

--10.
CREATE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO AS 학번, 
            STUDENT_NAME AS 학생이름, 
            STUDENT_ADDRESS AS 주소
        FROM TB_STUDENT);

--11. VIEW를 만들때 SELECT문에서 ORDER BY를 사용할 수 없다. 
CREATE VIEW VW_지도면담
AS (SELECT STUDENT_NAME AS 학생이름, 
            DEPARTMENT_NAME AS 학과이름, 
            PROFESSOR_NAME AS 지도교수이름
        FROM TB_STUDENT
        JOIN TB_DEPARTMENT 
            ON TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
        LEFT JOIN TB_PROFESSOR 
            ON TB_STUDENT.COACH_PROFESSOR_NO = TB_PROFESSOR.PROFESSOR_NO);

--12.
CREATE VIEW VW_학과별학생수
AS (SELECT DEPARTMENT_NAME, COUNT(*) AS STUDENT_COUNT
        FROM TB_STUDENT
        JOIN TB_DEPARTMENT 
            ON TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
        GROUP BY DEPARTMENT_NAME);
        
--13.
UPDATE VW_학생일반정보
SET 학생이름 = '신동호'
WHERE 학번 = 'A213046';

--14.
CREATE OR REPLACE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO AS 학번, 
            STUDENT_NAME AS 학생이름, 
            STUDENT_ADDRESS AS 주소
        FROM TB_STUDENT)
WITH READ ONLY;

--15.
SELECT CLASS_NO, CLASS_NAME, COUNT
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(*) AS COUNT
        FROM TB_GRADE
        JOIN TB_CLASS USING(CLASS_NO)
        WHERE SUBSTR(TERM_NO, 1, 4) >= (SELECT MAX(SUBSTR(TERM_NO, 1, 4)) - 3
                                            FROM TB_GRADE)
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY COUNT(*) DESC)
WHERE ROWNUM <= 3;

SELECT 과목번호, 과목이름, "누적수강생수(명)"
FROM (SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
      FROM TB_GRADE
           JOIN TB_CLASS USING(CLASS_NO)
      WHERE TERM_NO LIKE '2009%'
            OR TERM_NO LIKE '2008%'
            OR TERM_NO LIKE '2007%'
            OR TERM_NO LIKE '2006%'
            OR TERM_NO LIKE '2005%'
      GROUP BY CLASS_NO, CLASS_NAME
      ORDER BY 3 DESC)
WHERE ROWNUM <= 3;