-- 사용자 계정 생성
CREATE USER c##JDBC IDENTIFIED BY JDBC;


-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##JDBC;


-- 테이블스페이스 설정
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP TABLE TEST;

CREATE TABLE TEST(
  TNO NUMBER PRIMARY KEY,
  TNAME VARCHAR2(100) NOT NULL,
  TDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN('M', 'E')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(50),
    ENROLL 
);

CREATE SEQUENCE SEQ_USERNO
NOCACHE;
